/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/_account'
import { Route as AuthenticatedCartRouteImport } from './routes/_authenticated/cart'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedFlashDealsRouteImport } from './routes/_authenticated/flash-deals'
import { Route as AuthenticatedHowItWorksRouteImport } from './routes/_authenticated/how-it-works'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthenticatedAccountAddressesRouteImport } from './routes/_authenticated/_account/addresses'
import { Route as AuthenticatedAccountNotificationsRouteImport } from './routes/_authenticated/_account/notifications'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/_account/orders'
import { Route as AuthenticatedAccountOverviewRouteImport } from './routes/_authenticated/_account/overview'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/_account/profile'
import { Route as AuthenticatedAccountReturnsRouteImport } from './routes/_authenticated/_account/returns'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated/_account/settings'
import { Route as AuthenticatedAccountSupportRouteImport } from './routes/_authenticated/_account/support'
import { Route as AuthenticatedAccountWalletRouteImport } from './routes/_authenticated/_account/wallet'
import { Route as AuthenticatedAccountWishlistRouteImport } from './routes/_authenticated/_account/wishlist'
import { Route as AuthenticatedHomeIndexRouteImport } from './routes/_authenticated/_home/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedCategoriesIdRouteImport } from './routes/_authenticated/categories/$id'
import { Route as AuthenticatedFlashDealsIndexRouteImport } from './routes/_authenticated/flash-deals/index'
import { Route as AuthenticatedFlashDealsIdRouteImport } from './routes/_authenticated/flash-deals/$id'
import { Route as AuthenticatedFlashDealsProductsIndexRouteImport } from './routes/_authenticated/flash-deals/products/index'
import { Route as AuthenticatedFlashDealsProductsIdRouteImport } from './routes/_authenticated/flash-deals/products/$id'
import { Route as AuthenticatedFlashDealsRegisterIdRouteImport } from './routes/_authenticated/flash-deals/register/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/_account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCartRoute = AuthenticatedCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlashDealsRoute = AuthenticatedFlashDealsRouteImport.update({
  id: '/flash-deals',
  path: '/flash-deals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHowItWorksRoute = AuthenticatedHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAccountAddressesRoute =
  AuthenticatedAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountNotificationsRoute =
  AuthenticatedAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountOverviewRoute =
  AuthenticatedAccountOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountReturnsRoute =
  AuthenticatedAccountReturnsRouteImport.update({
    id: '/returns',
    path: '/returns',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountSupportRoute =
  AuthenticatedAccountSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountWalletRoute =
  AuthenticatedAccountWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountWishlistRoute =
  AuthenticatedAccountWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCategoriesRoute,
  } as any)
const AuthenticatedCategoriesIdRoute =
  AuthenticatedCategoriesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCategoriesRoute,
  } as any)
const AuthenticatedFlashDealsIndexRoute =
  AuthenticatedFlashDealsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFlashDealsRoute,
  } as any)
const AuthenticatedFlashDealsIdRoute =
  AuthenticatedFlashDealsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFlashDealsRoute,
  } as any)
const AuthenticatedFlashDealsProductsIndexRoute =
  AuthenticatedFlashDealsProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedFlashDealsRoute,
  } as any)
const AuthenticatedFlashDealsProductsIdRoute =
  AuthenticatedFlashDealsProductsIdRouteImport.update({
    id: '/products/$id',
    path: '/products/$id',
    getParentRoute: () => AuthenticatedFlashDealsRoute,
  } as any)
const AuthenticatedFlashDealsRegisterIdRoute =
  AuthenticatedFlashDealsRegisterIdRouteImport.update({
    id: '/register/$id',
    path: '/register/$id',
    getParentRoute: () => AuthenticatedFlashDealsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedHomeIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/cart': typeof AuthenticatedCartRoute
  '/categories': typeof AuthenticatedCategoriesRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/flash-deals': typeof AuthenticatedFlashDealsRouteWithChildren
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/addresses': typeof AuthenticatedAccountAddressesRoute
  '/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/orders': typeof AuthenticatedAccountOrdersRoute
  '/overview': typeof AuthenticatedAccountOverviewRoute
  '/profile': typeof AuthenticatedAccountProfileRoute
  '/returns': typeof AuthenticatedAccountReturnsRoute
  '/settings': typeof AuthenticatedAccountSettingsRoute
  '/support': typeof AuthenticatedAccountSupportRoute
  '/wallet': typeof AuthenticatedAccountWalletRoute
  '/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/categories/$id': typeof AuthenticatedCategoriesIdRoute
  '/flash-deals/$id': typeof AuthenticatedFlashDealsIdRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/flash-deals/': typeof AuthenticatedFlashDealsIndexRoute
  '/flash-deals/products/$id': typeof AuthenticatedFlashDealsProductsIdRoute
  '/flash-deals/register/$id': typeof AuthenticatedFlashDealsRegisterIdRoute
  '/flash-deals/products/': typeof AuthenticatedFlashDealsProductsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/': typeof AuthenticatedHomeIndexRoute
  '/cart': typeof AuthenticatedCartRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/addresses': typeof AuthenticatedAccountAddressesRoute
  '/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/orders': typeof AuthenticatedAccountOrdersRoute
  '/overview': typeof AuthenticatedAccountOverviewRoute
  '/profile': typeof AuthenticatedAccountProfileRoute
  '/returns': typeof AuthenticatedAccountReturnsRoute
  '/settings': typeof AuthenticatedAccountSettingsRoute
  '/support': typeof AuthenticatedAccountSupportRoute
  '/wallet': typeof AuthenticatedAccountWalletRoute
  '/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/categories/$id': typeof AuthenticatedCategoriesIdRoute
  '/flash-deals/$id': typeof AuthenticatedFlashDealsIdRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/flash-deals': typeof AuthenticatedFlashDealsIndexRoute
  '/flash-deals/products/$id': typeof AuthenticatedFlashDealsProductsIdRoute
  '/flash-deals/register/$id': typeof AuthenticatedFlashDealsRegisterIdRoute
  '/flash-deals/products': typeof AuthenticatedFlashDealsProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/_account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/cart': typeof AuthenticatedCartRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/flash-deals': typeof AuthenticatedFlashDealsRouteWithChildren
  '/_authenticated/how-it-works': typeof AuthenticatedHowItWorksRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_authenticated/_account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/_authenticated/_account/notifications': typeof AuthenticatedAccountNotificationsRoute
  '/_authenticated/_account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/_account/overview': typeof AuthenticatedAccountOverviewRoute
  '/_authenticated/_account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/_account/returns': typeof AuthenticatedAccountReturnsRoute
  '/_authenticated/_account/settings': typeof AuthenticatedAccountSettingsRoute
  '/_authenticated/_account/support': typeof AuthenticatedAccountSupportRoute
  '/_authenticated/_account/wallet': typeof AuthenticatedAccountWalletRoute
  '/_authenticated/_account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/_authenticated/categories/$id': typeof AuthenticatedCategoriesIdRoute
  '/_authenticated/flash-deals/$id': typeof AuthenticatedFlashDealsIdRoute
  '/_authenticated/_home/': typeof AuthenticatedHomeIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/flash-deals/': typeof AuthenticatedFlashDealsIndexRoute
  '/_authenticated/flash-deals/products/$id': typeof AuthenticatedFlashDealsProductsIdRoute
  '/_authenticated/flash-deals/register/$id': typeof AuthenticatedFlashDealsRegisterIdRoute
  '/_authenticated/flash-deals/products/': typeof AuthenticatedFlashDealsProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/flash-deals'
    | '/how-it-works'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/addresses'
    | '/notifications'
    | '/orders'
    | '/overview'
    | '/profile'
    | '/returns'
    | '/settings'
    | '/support'
    | '/wallet'
    | '/wishlist'
    | '/categories/$id'
    | '/flash-deals/$id'
    | '/categories/'
    | '/flash-deals/'
    | '/flash-deals/products/$id'
    | '/flash-deals/register/$id'
    | '/flash-deals/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/cart'
    | '/checkout'
    | '/how-it-works'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/addresses'
    | '/notifications'
    | '/orders'
    | '/overview'
    | '/profile'
    | '/returns'
    | '/settings'
    | '/support'
    | '/wallet'
    | '/wishlist'
    | '/categories/$id'
    | '/flash-deals/$id'
    | '/categories'
    | '/flash-deals'
    | '/flash-deals/products/$id'
    | '/flash-deals/register/$id'
    | '/flash-deals/products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_account'
    | '/_authenticated/cart'
    | '/_authenticated/categories'
    | '/_authenticated/checkout'
    | '/_authenticated/flash-deals'
    | '/_authenticated/how-it-works'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_authenticated/_account/addresses'
    | '/_authenticated/_account/notifications'
    | '/_authenticated/_account/orders'
    | '/_authenticated/_account/overview'
    | '/_authenticated/_account/profile'
    | '/_authenticated/_account/returns'
    | '/_authenticated/_account/settings'
    | '/_authenticated/_account/support'
    | '/_authenticated/_account/wallet'
    | '/_authenticated/_account/wishlist'
    | '/_authenticated/categories/$id'
    | '/_authenticated/flash-deals/$id'
    | '/_authenticated/_home/'
    | '/_authenticated/categories/'
    | '/_authenticated/flash-deals/'
    | '/_authenticated/flash-deals/products/$id'
    | '/_authenticated/flash-deals/register/$id'
    | '/_authenticated/flash-deals/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_account': {
      id: '/_authenticated/_account'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cart': {
      id: '/_authenticated/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedCartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flash-deals': {
      id: '/_authenticated/flash-deals'
      path: '/flash-deals'
      fullPath: '/flash-deals'
      preLoaderRoute: typeof AuthenticatedFlashDealsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/how-it-works': {
      id: '/_authenticated/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof AuthenticatedHowItWorksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/_account/addresses': {
      id: '/_authenticated/_account/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_account/notifications': {
      id: '/_authenticated/_account/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedAccountNotificationsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_account/orders': {
      id: '/_authenticated/_account/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_account/overview': {
      id: '/_authenticated/_account/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedAccountOverviewRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_account/profile': {
      id: '/_authenticated/_account/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_account/returns': {
      id: '/_authenticated/_account/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedAccountReturnsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_account/settings': {
      id: '/_authenticated/_account/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_account/support': {
      id: '/_authenticated/_account/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedAccountSupportRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_account/wallet': {
      id: '/_authenticated/_account/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedAccountWalletRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_account/wishlist': {
      id: '/_authenticated/_account/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedAccountWishlistRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/_home/': {
      id: '/_authenticated/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedHomeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedCategoriesRoute
    }
    '/_authenticated/categories/$id': {
      id: '/_authenticated/categories/$id'
      path: '/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof AuthenticatedCategoriesIdRouteImport
      parentRoute: typeof AuthenticatedCategoriesRoute
    }
    '/_authenticated/flash-deals/': {
      id: '/_authenticated/flash-deals/'
      path: '/'
      fullPath: '/flash-deals/'
      preLoaderRoute: typeof AuthenticatedFlashDealsIndexRouteImport
      parentRoute: typeof AuthenticatedFlashDealsRoute
    }
    '/_authenticated/flash-deals/$id': {
      id: '/_authenticated/flash-deals/$id'
      path: '/$id'
      fullPath: '/flash-deals/$id'
      preLoaderRoute: typeof AuthenticatedFlashDealsIdRouteImport
      parentRoute: typeof AuthenticatedFlashDealsRoute
    }
    '/_authenticated/flash-deals/products/': {
      id: '/_authenticated/flash-deals/products/'
      path: '/products'
      fullPath: '/flash-deals/products/'
      preLoaderRoute: typeof AuthenticatedFlashDealsProductsIndexRouteImport
      parentRoute: typeof AuthenticatedFlashDealsRoute
    }
    '/_authenticated/flash-deals/products/$id': {
      id: '/_authenticated/flash-deals/products/$id'
      path: '/products/$id'
      fullPath: '/flash-deals/products/$id'
      preLoaderRoute: typeof AuthenticatedFlashDealsProductsIdRouteImport
      parentRoute: typeof AuthenticatedFlashDealsRoute
    }
    '/_authenticated/flash-deals/register/$id': {
      id: '/_authenticated/flash-deals/register/$id'
      path: '/register/$id'
      fullPath: '/flash-deals/register/$id'
      preLoaderRoute: typeof AuthenticatedFlashDealsRegisterIdRouteImport
      parentRoute: typeof AuthenticatedFlashDealsRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAddressesRoute: typeof AuthenticatedAccountAddressesRoute
  AuthenticatedAccountNotificationsRoute: typeof AuthenticatedAccountNotificationsRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountOverviewRoute: typeof AuthenticatedAccountOverviewRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountReturnsRoute: typeof AuthenticatedAccountReturnsRoute
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRoute
  AuthenticatedAccountSupportRoute: typeof AuthenticatedAccountSupportRoute
  AuthenticatedAccountWalletRoute: typeof AuthenticatedAccountWalletRoute
  AuthenticatedAccountWishlistRoute: typeof AuthenticatedAccountWishlistRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAddressesRoute: AuthenticatedAccountAddressesRoute,
  AuthenticatedAccountNotificationsRoute:
    AuthenticatedAccountNotificationsRoute,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
  AuthenticatedAccountOverviewRoute: AuthenticatedAccountOverviewRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountReturnsRoute: AuthenticatedAccountReturnsRoute,
  AuthenticatedAccountSettingsRoute: AuthenticatedAccountSettingsRoute,
  AuthenticatedAccountSupportRoute: AuthenticatedAccountSupportRoute,
  AuthenticatedAccountWalletRoute: AuthenticatedAccountWalletRoute,
  AuthenticatedAccountWishlistRoute: AuthenticatedAccountWishlistRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedCategoriesRouteChildren {
  AuthenticatedCategoriesIdRoute: typeof AuthenticatedCategoriesIdRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
}

const AuthenticatedCategoriesRouteChildren: AuthenticatedCategoriesRouteChildren =
  {
    AuthenticatedCategoriesIdRoute: AuthenticatedCategoriesIdRoute,
    AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  }

const AuthenticatedCategoriesRouteWithChildren =
  AuthenticatedCategoriesRoute._addFileChildren(
    AuthenticatedCategoriesRouteChildren,
  )

interface AuthenticatedFlashDealsRouteChildren {
  AuthenticatedFlashDealsIdRoute: typeof AuthenticatedFlashDealsIdRoute
  AuthenticatedFlashDealsIndexRoute: typeof AuthenticatedFlashDealsIndexRoute
  AuthenticatedFlashDealsProductsIdRoute: typeof AuthenticatedFlashDealsProductsIdRoute
  AuthenticatedFlashDealsRegisterIdRoute: typeof AuthenticatedFlashDealsRegisterIdRoute
  AuthenticatedFlashDealsProductsIndexRoute: typeof AuthenticatedFlashDealsProductsIndexRoute
}

const AuthenticatedFlashDealsRouteChildren: AuthenticatedFlashDealsRouteChildren =
  {
    AuthenticatedFlashDealsIdRoute: AuthenticatedFlashDealsIdRoute,
    AuthenticatedFlashDealsIndexRoute: AuthenticatedFlashDealsIndexRoute,
    AuthenticatedFlashDealsProductsIdRoute:
      AuthenticatedFlashDealsProductsIdRoute,
    AuthenticatedFlashDealsRegisterIdRoute:
      AuthenticatedFlashDealsRegisterIdRoute,
    AuthenticatedFlashDealsProductsIndexRoute:
      AuthenticatedFlashDealsProductsIndexRoute,
  }

const AuthenticatedFlashDealsRouteWithChildren =
  AuthenticatedFlashDealsRoute._addFileChildren(
    AuthenticatedFlashDealsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedCartRoute: typeof AuthenticatedCartRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedFlashDealsRoute: typeof AuthenticatedFlashDealsRouteWithChildren
  AuthenticatedHowItWorksRoute: typeof AuthenticatedHowItWorksRoute
  AuthenticatedHomeIndexRoute: typeof AuthenticatedHomeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedCartRoute: AuthenticatedCartRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedFlashDealsRoute: AuthenticatedFlashDealsRouteWithChildren,
  AuthenticatedHowItWorksRoute: AuthenticatedHowItWorksRoute,
  AuthenticatedHomeIndexRoute: AuthenticatedHomeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
