import {
  Product1,
  Product2,
  Product3,
  Product4,
  CategoryElectronics,
  CategoryHomeAppliances,
  CategoryFashion,
  CategoryAccessories,
  CategoryBeauty,
  CategorySports,
} from "@/assets/images";

export const deals = [
  {
    id: 1,
    status: "Live Now",
    badge: "#017B24",
    badgeText: "text-white",
    image: Product1,
    title: "Summer Electronics Flash Sale",
    description: "Unbeatable deals on top electronics.",
    products: 12,
    minOrder: "Min. Order ₹ 5,000",
    button: "Register for ₹1",
    buttonStyle: "orange",
    type: "live",
  },
  {
    id: 2,
    status: "Starting Soon",
    badge: "#FEB305",
    badgeText: "text-black",
    image: Product2,
    title: "Home Appliances Bonanza",
    description: "Exclusive discounts on premium appliances.",
    products: 20,
    minOrder: "Min. Order ₹ 5,000",
    button: "Notify Me",
    buttonStyle: "yellow",
    type: "starting",
  },
  {
    id: 3,
    status: "Upcoming",
    badge: " #4E148C",
    badgeText: "text-white",
    image: Product3,
    title: "Fashion Mega Deals",
    description: "Trending styles at crazy prices.",
    products: 18,
    minOrder: "Min. Order ₹ 5,000",
    button: "Notify Me",
    buttonStyle: "primary",
    type: "upcoming",
  },
  {
    id: 4,
    status: "Ended",
    badge: "#555555",
    badgeText: "text-white",
    image: Product4,
    title: "Smartphone Clearance",
    description: "This flash deal has ended.",
    products: 15,
    minOrder: "Min. Order ₹ 5,000",
    button: "Closed",
    buttonStyle: "white",
    type: "ended",
  },
];

export const categories = [
  {
    id: 1,
    title: "Electronics",
    products: 121,
    image: CategoryElectronics,
    status: "Active",
  },
  {
    id: 2,
    title: "Home Appliances",
    products: 88,
    image: CategoryHomeAppliances,
    status: "Active",
  },
  {
    id: 3,
    title: "Fashion",
    products: 156,
    image: CategoryFashion,
    status: "Active",
  },
  {
    id: 4,
    title: "Accessories",
    products: 95,
    image: CategoryAccessories,
    status: "Active",
  },
  {
    id: 5,
    title: "Beauty",
    products: 79,
    image: CategoryBeauty,
    status: "Active",
  },
  {
    id: 6,
    title: "Sports",
    products: 32,
    image: CategorySports,
    status: "Active",
  },
  {
    id: 7,
    title: "Furniture",
    products: 45,
    image: CategoryHomeAppliances, // Fallback image for now
    status: "Upcoming",
  },
  {
    id: 8,
    title: "Automotive",
    products: 12,
    image: CategoryAccessories, // Fallback image for now
    status: "Upcoming",
  },
];
